# Generated by Django 4.1.5 on 2023-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_filtroanio_filtromes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('1', 'Enero'), ('1', 'Febrero'), ('1', 'Marzo'), ('1', 'Abril'), ('1', 'Mayo'), ('1', 'Junio'), ('1', 'Julio'), ('1', 'Agosto'), ('1', 'Septiembre'), ('1', 'Noviembre'), ('1', 'Diciembre')], default='1', max_length=60, verbose_name='mes')),
                ('anio', models.TextField(blank=True, choices=[('2014', '2014'), ('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='2023', null=True, verbose_name='anio')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='FiltroAnio',
        ),
        migrations.DeleteModel(
            name='FiltroMes',
        ),
    ]
