# Generated by Django 4.1.5 on 2023-03-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas', '0004_filtros_delete_filtroanio_delete_filtromes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filtros',
        ),
    ]
