# Generated by Django 4.1.5 on 2023-03-24 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nomina', '0005_delete_filtros'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeJornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_jornada_global', models.DateTimeField(null=True, verbose_name='Inicio Jornada')),
                ('salida_jornada_global', models.DateTimeField(null=True, verbose_name='Salida Jornada')),
                ('inicio_descanso_global', models.DateTimeField(blank=True, null=True, verbose_name='Inicio Descanso')),
                ('salida_descanso_global', models.DateTimeField(blank=True, null=True, verbose_name='Salida Descanso')),
                ('inicio_descanso_global2', models.DateTimeField(blank=True, null=True, verbose_name='Inicio Descanso 2')),
                ('salida_descanso_global2', models.DateTimeField(blank=True, null=True, verbose_name='Salida Descanso 2')),
                ('jornada_legal', models.IntegerField(default=8, verbose_name='Jornada Legal')),
                ('fh_transaccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha De Transacción')),
                ('total_horas', models.FloatField(default=0, verbose_name='Total Horas')),
                ('diurnas_totales', models.FloatField(default=0, verbose_name='Horas Diurnas')),
                ('nocturnas_totales', models.FloatField(default=0, verbose_name='Horas Nocturnas')),
                ('extras_diurnas_totales', models.FloatField(default=0, verbose_name='Horas Extras Diurnas')),
                ('extras_nocturnos_totales', models.FloatField(default=0, verbose_name=' Horas Extras Nocturnas')),
                ('diurnos_festivo_totales', models.FloatField(default=0, verbose_name='Horas Diurnas Festivas')),
                ('nocturnos_festivo_totales', models.FloatField(default=0, verbose_name='Horas Nocturnas Festivas')),
                ('extras_diurnos_festivo_totales', models.FloatField(default=0, verbose_name='Horas Extras Diurnas Festivas')),
                ('extras_nocturnos_festivo_totales', models.FloatField(default=0, verbose_name='Horas Extras Nocturnas Festivas')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nomina.empleados')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creada Por')),
            ],
            options={
                'ordering': ['empleado'],
            },
        ),
    ]
