# Generated by Django 4.2 on 2023-05-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0007_alter_empleados_empresa_and_more'),
        ('nomina', '0008_alter_empleados_empresa'),
    ]

    operations = [
    ]
