# Generated by Django 4.1.7 on 2023-03-05 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='generaextras',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, verbose_name='Genera Extras'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='ingreso',
            field=models.DateField(max_length=10, null=True, verbose_name='Fecha Ingreso'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='retiro',
            field=models.DateField(max_length=10, null=True, verbose_name='Fecha Retiro'),
        ),
    ]
