# Generated by Django 4.1.7 on 2023-03-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas', '0002_empleados_generaextras_empleados_ingreso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='area',
            field=models.CharField(choices=[('Administracion', 'Administracion'), ('Compras', 'Compras'), ('Comercial', 'Comercial'), ('Exportaciones', 'Exportaciones'), ('Gestion TI', 'Gestion TI'), ('Logistica', 'Logistica'), ('Operaciones', 'Operaciones')], max_length=33, verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='retiro',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Fecha Retiro'),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Salario'),
        ),
    ]
