# Generated by Django 4.1.5 on 2023-03-22 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_horas', '0002_festivos'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroAnio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.CharField(max_length=60, verbose_name='anio')),
            ],
            options={
                'ordering': ['anio'],
            },
        ),
        migrations.CreateModel(
            name='FiltroMes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=60, verbose_name='mes')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
